// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: internal/proto/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TgUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       int64                        `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SessionKey   string                       `protobuf:"bytes,2,opt,name=sessionKey,proto3" json:"sessionKey,omitempty"`
	Devices      []*TgUser_Device             `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	State        string                       `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	SearchResult []*TgUser_SignedSearchResult `protobuf:"bytes,5,rep,name=searchResult,proto3" json:"searchResult,omitempty"`
	FilmResult   []*TgUser_SignedFilmResult   `protobuf:"bytes,6,rep,name=filmResult,proto3" json:"filmResult,omitempty"`
}

func (x *TgUser) Reset() {
	*x = TgUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TgUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TgUser) ProtoMessage() {}

func (x *TgUser) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TgUser.ProtoReflect.Descriptor instead.
func (*TgUser) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *TgUser) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *TgUser) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *TgUser) GetDevices() []*TgUser_Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *TgUser) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TgUser) GetSearchResult() []*TgUser_SignedSearchResult {
	if x != nil {
		return x.SearchResult
	}
	return nil
}

func (x *TgUser) GetFilmResult() []*TgUser_SignedFilmResult {
	if x != nil {
		return x.FilmResult
	}
	return nil
}

type RegisterNewClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionKey string `protobuf:"bytes,1,opt,name=sessionKey,proto3" json:"sessionKey,omitempty"`
	DeviceID   string `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	DeviceName string `protobuf:"bytes,3,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
}

func (x *RegisterNewClient) Reset() {
	*x = RegisterNewClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterNewClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewClient) ProtoMessage() {}

func (x *RegisterNewClient) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewClient.ProtoReflect.Descriptor instead.
func (*RegisterNewClient) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNewClient) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *RegisterNewClient) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *RegisterNewClient) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

type ClientToServerChannelMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Report:
	//
	//	*ClientToServerChannelMessage_DownloadStarted_
	//	*ClientToServerChannelMessage_Downloads
	Report isClientToServerChannelMessage_Report `protobuf_oneof:"Report"`
}

func (x *ClientToServerChannelMessage) Reset() {
	*x = ClientToServerChannelMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientToServerChannelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToServerChannelMessage) ProtoMessage() {}

func (x *ClientToServerChannelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToServerChannelMessage.ProtoReflect.Descriptor instead.
func (*ClientToServerChannelMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{2}
}

func (m *ClientToServerChannelMessage) GetReport() isClientToServerChannelMessage_Report {
	if m != nil {
		return m.Report
	}
	return nil
}

func (x *ClientToServerChannelMessage) GetDownloadStarted() *ClientToServerChannelMessage_DownloadStarted {
	if x, ok := x.GetReport().(*ClientToServerChannelMessage_DownloadStarted_); ok {
		return x.DownloadStarted
	}
	return nil
}

func (x *ClientToServerChannelMessage) GetDownloads() *ClientToServerChannelMessage_CurrentDownloads {
	if x, ok := x.GetReport().(*ClientToServerChannelMessage_Downloads); ok {
		return x.Downloads
	}
	return nil
}

type isClientToServerChannelMessage_Report interface {
	isClientToServerChannelMessage_Report()
}

type ClientToServerChannelMessage_DownloadStarted_ struct {
	DownloadStarted *ClientToServerChannelMessage_DownloadStarted `protobuf:"bytes,1,opt,name=downloadStarted,proto3,oneof"`
}

type ClientToServerChannelMessage_Downloads struct {
	Downloads *ClientToServerChannelMessage_CurrentDownloads `protobuf:"bytes,2,opt,name=downloads,proto3,oneof"`
}

func (*ClientToServerChannelMessage_DownloadStarted_) isClientToServerChannelMessage_Report() {}

func (*ClientToServerChannelMessage_Downloads) isClientToServerChannelMessage_Report() {}

type ServerToClientChannelMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//
	//	*ServerToClientChannelMessage_Start
	//	*ServerToClientChannelMessage_Stop
	//	*ServerToClientChannelMessage_List
	Action isServerToClientChannelMessage_Action `protobuf_oneof:"Action"`
}

func (x *ServerToClientChannelMessage) Reset() {
	*x = ServerToClientChannelMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerToClientChannelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToClientChannelMessage) ProtoMessage() {}

func (x *ServerToClientChannelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToClientChannelMessage.ProtoReflect.Descriptor instead.
func (*ServerToClientChannelMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{3}
}

func (m *ServerToClientChannelMessage) GetAction() isServerToClientChannelMessage_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *ServerToClientChannelMessage) GetStart() *ServerToClientChannelMessage_StartDownload {
	if x, ok := x.GetAction().(*ServerToClientChannelMessage_Start); ok {
		return x.Start
	}
	return nil
}

func (x *ServerToClientChannelMessage) GetStop() *ServerToClientChannelMessage_StopDownload {
	if x, ok := x.GetAction().(*ServerToClientChannelMessage_Stop); ok {
		return x.Stop
	}
	return nil
}

func (x *ServerToClientChannelMessage) GetList() *ServerToClientChannelMessage_ListDownloads {
	if x, ok := x.GetAction().(*ServerToClientChannelMessage_List); ok {
		return x.List
	}
	return nil
}

type isServerToClientChannelMessage_Action interface {
	isServerToClientChannelMessage_Action()
}

type ServerToClientChannelMessage_Start struct {
	Start *ServerToClientChannelMessage_StartDownload `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ServerToClientChannelMessage_Stop struct {
	Stop *ServerToClientChannelMessage_StopDownload `protobuf:"bytes,2,opt,name=stop,proto3,oneof"`
}

type ServerToClientChannelMessage_List struct {
	List *ServerToClientChannelMessage_ListDownloads `protobuf:"bytes,3,opt,name=list,proto3,oneof"`
}

func (*ServerToClientChannelMessage_Start) isServerToClientChannelMessage_Action() {}

func (*ServerToClientChannelMessage_Stop) isServerToClientChannelMessage_Action() {}

func (*ServerToClientChannelMessage_List) isServerToClientChannelMessage_Action() {}

type TgUser_SignedSearchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SearchResult *TgUser_SignedSearchResult_SearchResult `protobuf:"bytes,2,opt,name=searchResult,proto3" json:"searchResult,omitempty"`
}

func (x *TgUser_SignedSearchResult) Reset() {
	*x = TgUser_SignedSearchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TgUser_SignedSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TgUser_SignedSearchResult) ProtoMessage() {}

func (x *TgUser_SignedSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TgUser_SignedSearchResult.ProtoReflect.Descriptor instead.
func (*TgUser_SignedSearchResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TgUser_SignedSearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TgUser_SignedSearchResult) GetSearchResult() *TgUser_SignedSearchResult_SearchResult {
	if x != nil {
		return x.SearchResult
	}
	return nil
}

type TgUser_SignedFilmResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FilmResult *TgUser_SignedFilmResult_FilmResult `protobuf:"bytes,2,opt,name=filmResult,proto3" json:"filmResult,omitempty"`
}

func (x *TgUser_SignedFilmResult) Reset() {
	*x = TgUser_SignedFilmResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TgUser_SignedFilmResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TgUser_SignedFilmResult) ProtoMessage() {}

func (x *TgUser_SignedFilmResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TgUser_SignedFilmResult.ProtoReflect.Descriptor instead.
func (*TgUser_SignedFilmResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{0, 1}
}

func (x *TgUser_SignedFilmResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TgUser_SignedFilmResult) GetFilmResult() *TgUser_SignedFilmResult_FilmResult {
	if x != nil {
		return x.FilmResult
	}
	return nil
}

type TgUser_Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TgUser_Device) Reset() {
	*x = TgUser_Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TgUser_Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TgUser_Device) ProtoMessage() {}

func (x *TgUser_Device) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TgUser_Device.ProtoReflect.Descriptor instead.
func (*TgUser_Device) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{0, 2}
}

func (x *TgUser_Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TgUser_Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TgUser_SignedSearchResult_SearchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Href  string `protobuf:"bytes,2,opt,name=href,proto3" json:"href,omitempty"`
}

func (x *TgUser_SignedSearchResult_SearchResult) Reset() {
	*x = TgUser_SignedSearchResult_SearchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TgUser_SignedSearchResult_SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TgUser_SignedSearchResult_SearchResult) ProtoMessage() {}

func (x *TgUser_SignedSearchResult_SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TgUser_SignedSearchResult_SearchResult.ProtoReflect.Descriptor instead.
func (*TgUser_SignedSearchResult_SearchResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *TgUser_SignedSearchResult_SearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TgUser_SignedSearchResult_SearchResult) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

type TgUser_SignedFilmResult_FilmResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quality              string `protobuf:"bytes,1,opt,name=quality,proto3" json:"quality,omitempty"`
	TranslationVoiceover string `protobuf:"bytes,2,opt,name=translationVoiceover,proto3" json:"translationVoiceover,omitempty"`
	Author               string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	FileFormat           string `protobuf:"bytes,4,opt,name=fileFormat,proto3" json:"fileFormat,omitempty"`
	Size                 string `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	Magnet               string `protobuf:"bytes,6,opt,name=magnet,proto3" json:"magnet,omitempty"`
}

func (x *TgUser_SignedFilmResult_FilmResult) Reset() {
	*x = TgUser_SignedFilmResult_FilmResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TgUser_SignedFilmResult_FilmResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TgUser_SignedFilmResult_FilmResult) ProtoMessage() {}

func (x *TgUser_SignedFilmResult_FilmResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TgUser_SignedFilmResult_FilmResult.ProtoReflect.Descriptor instead.
func (*TgUser_SignedFilmResult_FilmResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *TgUser_SignedFilmResult_FilmResult) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *TgUser_SignedFilmResult_FilmResult) GetTranslationVoiceover() string {
	if x != nil {
		return x.TranslationVoiceover
	}
	return ""
}

func (x *TgUser_SignedFilmResult_FilmResult) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *TgUser_SignedFilmResult_FilmResult) GetFileFormat() string {
	if x != nil {
		return x.FileFormat
	}
	return ""
}

func (x *TgUser_SignedFilmResult_FilmResult) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *TgUser_SignedFilmResult_FilmResult) GetMagnet() string {
	if x != nil {
		return x.Magnet
	}
	return ""
}

type ClientToServerChannelMessage_DownloadStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DownloadID string `protobuf:"bytes,1,opt,name=downloadID,proto3" json:"downloadID,omitempty"`
}

func (x *ClientToServerChannelMessage_DownloadStarted) Reset() {
	*x = ClientToServerChannelMessage_DownloadStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientToServerChannelMessage_DownloadStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToServerChannelMessage_DownloadStarted) ProtoMessage() {}

func (x *ClientToServerChannelMessage_DownloadStarted) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToServerChannelMessage_DownloadStarted.ProtoReflect.Descriptor instead.
func (*ClientToServerChannelMessage_DownloadStarted) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ClientToServerChannelMessage_DownloadStarted) GetDownloadID() string {
	if x != nil {
		return x.DownloadID
	}
	return ""
}

type ClientToServerChannelMessage_CurrentDownloads struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DownloadIDs []string `protobuf:"bytes,1,rep,name=downloadIDs,proto3" json:"downloadIDs,omitempty"`
}

func (x *ClientToServerChannelMessage_CurrentDownloads) Reset() {
	*x = ClientToServerChannelMessage_CurrentDownloads{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientToServerChannelMessage_CurrentDownloads) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToServerChannelMessage_CurrentDownloads) ProtoMessage() {}

func (x *ClientToServerChannelMessage_CurrentDownloads) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToServerChannelMessage_CurrentDownloads.ProtoReflect.Descriptor instead.
func (*ClientToServerChannelMessage_CurrentDownloads) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ClientToServerChannelMessage_CurrentDownloads) GetDownloadIDs() []string {
	if x != nil {
		return x.DownloadIDs
	}
	return nil
}

type ServerToClientChannelMessage_StartDownload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Href string `protobuf:"bytes,1,opt,name=href,proto3" json:"href,omitempty"`
}

func (x *ServerToClientChannelMessage_StartDownload) Reset() {
	*x = ServerToClientChannelMessage_StartDownload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerToClientChannelMessage_StartDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToClientChannelMessage_StartDownload) ProtoMessage() {}

func (x *ServerToClientChannelMessage_StartDownload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToClientChannelMessage_StartDownload.ProtoReflect.Descriptor instead.
func (*ServerToClientChannelMessage_StartDownload) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ServerToClientChannelMessage_StartDownload) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

type ServerToClientChannelMessage_StopDownload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DownloadID string `protobuf:"bytes,1,opt,name=downloadID,proto3" json:"downloadID,omitempty"`
}

func (x *ServerToClientChannelMessage_StopDownload) Reset() {
	*x = ServerToClientChannelMessage_StopDownload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerToClientChannelMessage_StopDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToClientChannelMessage_StopDownload) ProtoMessage() {}

func (x *ServerToClientChannelMessage_StopDownload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToClientChannelMessage_StopDownload.ProtoReflect.Descriptor instead.
func (*ServerToClientChannelMessage_StopDownload) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ServerToClientChannelMessage_StopDownload) GetDownloadID() string {
	if x != nil {
		return x.DownloadID
	}
	return ""
}

type ServerToClientChannelMessage_ListDownloads struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServerToClientChannelMessage_ListDownloads) Reset() {
	*x = ServerToClientChannelMessage_ListDownloads{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerToClientChannelMessage_ListDownloads) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToClientChannelMessage_ListDownloads) ProtoMessage() {}

func (x *ServerToClientChannelMessage_ListDownloads) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToClientChannelMessage_ListDownloads.ProtoReflect.Descriptor instead.
func (*ServerToClientChannelMessage_ListDownloads) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{3, 2}
}

var File_internal_proto_api_proto protoreflect.FileDescriptor

var file_internal_proto_api_proto_rawDesc = []byte{
	0x0a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x9f, 0x06, 0x0a, 0x06, 0x74, 0x67, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x4b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x67,
	0x55, 0x73, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x44, 0x0a, 0x0c, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x67, 0x55, 0x73, 0x65, 0x72, 0x2e,
	0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x0c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x3e, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x67, 0x55,
	0x73, 0x65, 0x72, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x6d, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x1a, 0xb1, 0x01, 0x0a, 0x12, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x51, 0x0a, 0x0c, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x67, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0c, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x38, 0x0a, 0x0c, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x72, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x72, 0x65, 0x66, 0x1a, 0xae, 0x02, 0x0a, 0x10, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x46,
	0x69, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x49, 0x0a, 0x0a, 0x66, 0x69, 0x6c,
	0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x67, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x46, 0x69,
	0x6c, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x6d, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x1a, 0xbe, 0x01, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x6d, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x32, 0x0a,
	0x14, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x6f, 0x69, 0x63,
	0x65, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x6f, 0x76, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x6c,
	0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66,
	0x69, 0x6c, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d,
	0x61, 0x67, 0x6e, 0x65, 0x74, 0x1a, 0x2c, 0x0a, 0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x6f, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e,
	0x65, 0x77, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0xc8, 0x02, 0x0a, 0x1c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54,
	0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x5f, 0x0a, 0x0f, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0f, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x54, 0x0a, 0x09, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x48,
	0x00, 0x52, 0x09, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x1a, 0x31, 0x0a, 0x0f,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x44, 0x1a,
	0x34, 0x0a, 0x10, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49,
	0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x49, 0x44, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x22,
	0xea, 0x02, 0x0a, 0x1c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x49, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x6f,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x46, 0x0a, 0x04, 0x73,
	0x74, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53,
	0x74, 0x6f, 0x70, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x04, 0x73,
	0x74, 0x6f, 0x70, 0x12, 0x47, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x73, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x23, 0x0a, 0x0d,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x72, 0x65,
	0x66, 0x1a, 0x2e, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x70, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49,
	0x44, 0x1a, 0x0f, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x10, 0x5a, 0x0e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_api_proto_rawDescOnce sync.Once
	file_internal_proto_api_proto_rawDescData = file_internal_proto_api_proto_rawDesc
)

func file_internal_proto_api_proto_rawDescGZIP() []byte {
	file_internal_proto_api_proto_rawDescOnce.Do(func() {
		file_internal_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_api_proto_rawDescData)
	})
	return file_internal_proto_api_proto_rawDescData
}

var file_internal_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_proto_api_proto_goTypes = []interface{}{
	(*TgUser)(nil),                                        // 0: proto.tgUser
	(*RegisterNewClient)(nil),                             // 1: proto.RegisterNewClient
	(*ClientToServerChannelMessage)(nil),                  // 2: proto.ClientToServerChannelMessage
	(*ServerToClientChannelMessage)(nil),                  // 3: proto.ServerToClientChannelMessage
	(*TgUser_SignedSearchResult)(nil),                     // 4: proto.tgUser.SignedSearchResult
	(*TgUser_SignedFilmResult)(nil),                       // 5: proto.tgUser.SignedFilmResult
	(*TgUser_Device)(nil),                                 // 6: proto.tgUser.Device
	(*TgUser_SignedSearchResult_SearchResult)(nil),        // 7: proto.tgUser.SignedSearchResult.SearchResult
	(*TgUser_SignedFilmResult_FilmResult)(nil),            // 8: proto.tgUser.SignedFilmResult.FilmResult
	(*ClientToServerChannelMessage_DownloadStarted)(nil),  // 9: proto.ClientToServerChannelMessage.DownloadStarted
	(*ClientToServerChannelMessage_CurrentDownloads)(nil), // 10: proto.ClientToServerChannelMessage.CurrentDownloads
	(*ServerToClientChannelMessage_StartDownload)(nil),    // 11: proto.ServerToClientChannelMessage.StartDownload
	(*ServerToClientChannelMessage_StopDownload)(nil),     // 12: proto.ServerToClientChannelMessage.StopDownload
	(*ServerToClientChannelMessage_ListDownloads)(nil),    // 13: proto.ServerToClientChannelMessage.ListDownloads
}
var file_internal_proto_api_proto_depIdxs = []int32{
	6,  // 0: proto.tgUser.devices:type_name -> proto.tgUser.Device
	4,  // 1: proto.tgUser.searchResult:type_name -> proto.tgUser.SignedSearchResult
	5,  // 2: proto.tgUser.filmResult:type_name -> proto.tgUser.SignedFilmResult
	9,  // 3: proto.ClientToServerChannelMessage.downloadStarted:type_name -> proto.ClientToServerChannelMessage.DownloadStarted
	10, // 4: proto.ClientToServerChannelMessage.downloads:type_name -> proto.ClientToServerChannelMessage.CurrentDownloads
	11, // 5: proto.ServerToClientChannelMessage.start:type_name -> proto.ServerToClientChannelMessage.StartDownload
	12, // 6: proto.ServerToClientChannelMessage.stop:type_name -> proto.ServerToClientChannelMessage.StopDownload
	13, // 7: proto.ServerToClientChannelMessage.list:type_name -> proto.ServerToClientChannelMessage.ListDownloads
	7,  // 8: proto.tgUser.SignedSearchResult.searchResult:type_name -> proto.tgUser.SignedSearchResult.SearchResult
	8,  // 9: proto.tgUser.SignedFilmResult.filmResult:type_name -> proto.tgUser.SignedFilmResult.FilmResult
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_proto_api_proto_init() }
func file_internal_proto_api_proto_init() {
	if File_internal_proto_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TgUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterNewClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientToServerChannelMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerToClientChannelMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TgUser_SignedSearchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TgUser_SignedFilmResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TgUser_Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TgUser_SignedSearchResult_SearchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TgUser_SignedFilmResult_FilmResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientToServerChannelMessage_DownloadStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientToServerChannelMessage_CurrentDownloads); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerToClientChannelMessage_StartDownload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerToClientChannelMessage_StopDownload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerToClientChannelMessage_ListDownloads); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_proto_api_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ClientToServerChannelMessage_DownloadStarted_)(nil),
		(*ClientToServerChannelMessage_Downloads)(nil),
	}
	file_internal_proto_api_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ServerToClientChannelMessage_Start)(nil),
		(*ServerToClientChannelMessage_Stop)(nil),
		(*ServerToClientChannelMessage_List)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_api_proto_goTypes,
		DependencyIndexes: file_internal_proto_api_proto_depIdxs,
		MessageInfos:      file_internal_proto_api_proto_msgTypes,
	}.Build()
	File_internal_proto_api_proto = out.File
	file_internal_proto_api_proto_rawDesc = nil
	file_internal_proto_api_proto_goTypes = nil
	file_internal_proto_api_proto_depIdxs = nil
}
