services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server.Dockerfile
    ports:
      - "42069:42069"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
